### ISSUE TITLE
Exclude part of document

### ISSUE THREAD

**Issue by lorenzoFabbri** [rchaput/acronyms#16]
What I'd like to happen is the following. Suppose the acronym `ci` is *confidence interval* or *CI*. If in one section of my document (let's say the abstract) I write `\acr{ci}` I'd still like to see *confidence interval (CI)*, but then in the main text I'd still like to see *confidence interval (CI)* the first time I use it.

**Comment by rchaput** [comment]
I've just release **acronyms** v2.0.0, which includes the newer shortcode syntax that may help you in this case.
Instead of using `\acr{ci}`, you can now use `{{< acr ci >}}`. To force having your acronyms appear as if it was the first usage, you can use `{{< acr ci first_use=true >}}` (which was not possible with the legacy `\acr{ci}` syntax).

I understand this can be cumbersome if you have a lot of acronyms, so I will work on a new feature that allows to reset the usage counters in the document, but in the meantime you can use this technique.
