### ISSUE TITLE
options to \printacronyms breaks section

### ISSUE THREAD

**Issue by jmehringer-iis** [rchaput/acronyms#3]
See this little `.qmd` file:

````
---
title: "Untitled"
format: 
    pdf:
        include-in-header:
            - text: |
                \usepackage{acro}
                \acsetup{patch/longtable=false}
filters: 
    - acronyms
acronyms:
    fromfile: acronyms.yml
    # You can insert the List Of Acronyms anywhere you want with `\printacronyms`
    insert_loa: false
keep-tex: true
---

# Introduction {#intro}

This paragraph mentions \acr{RL} for the first time.

```{=latex}
\printacronyms[heading=section]
```

And now, in this paragraph, \acr{RL} is in short form.
````

then, the `loa` is not printed with some fallback `Acronyms` section

![grafik](https://github.com/rchaput/acronyms/assets/126784821/fe490109-fa43-45c5-a217-ff33f79b1204)

This applies to all options specified for the `\printacronyms` command

**Comment by rchaput** [comment]
(Sorry for the delay, I'm trying to work on **acronyms**' issues when I have time)

I'm not sure what you're trying to do with `\printacronyms[heading=section]`?
Despite looking like a LaTeX command (which is confusing, I agree), this is actually just a hardcoded string that my filter looks for in the document. (`\acr{<KEY>}` works also similarly, but with a bit more details, because we need to retrieve the key; but neither of them are LaTeX commands).

So, for me, it seems logical that nothing happens, **acronyms** does not recognize the `\printacronyms` string.
The `Acronyms` header seems to come from your `acro` package, which is purely LaTeX, and thus does not have access to **acronyms**' data...

**Comment by jmehringer-iis** [comment]
Hi, no worries! I'm also busy, hence a late reply from me as well.

I guess what I wanted to do is displaying the LOA in my TOC, but without a chapter number, like in https://github.com/rchaput/acronyms/issues/6#issue-1863097713 

Since you're already working on this in the other issue, I'll close this one :)
Cheers!
